import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

import { QueryProvider } from '@/components/features/QueryProvider';
import { SandwichStack } from '@/components/templates/SandwichStack';
import { RootThemeWrap } from '@/theme/RootThemeWrap';

import '@/app/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="antialiased">
      <body>
        {/*
          AppRouterCacheProvider
          ----------
          Collects the CSS generated by the MUI System on the server,
          as Next.js is streaming chunks of the .html page to the client
        */}
        <AppRouterCacheProvider>
          <QueryProvider>
            <RootThemeWrap>
              <SandwichStack>{children}</SandwichStack>
            </RootThemeWrap>
          </QueryProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
